FROM plotly/heroku-docker-r:3.6.2_heroku18

# on build, copy application files
COPY . /app/

# install dependencies with init.R
RUN /usr/bin/R --no-init-file --no-save --quiet --slave -f /app/init.R

# here farrington_bystate_dash.R needs to match the name of the file which contains your app              
CMD cd /app && /usr/bin/R --no-save -f /app/farrington_bystate_dash.r
